<?php

declare(strict_types=1);

/**
 * Generates generated/A2A/Types/Meta/RequiredFields.php.
 *
 * The Python SDK validates `(google.api.field_behavior) = REQUIRED` by reading
 * field options off the descriptor at runtime. PHP's protobuf runtime does not
 * expose field options, so we read them once, here, from the serialized
 * FileDescriptorProto that buf already embedded in GPBMetadata/A2A.php, and
 * write them out as a plain lookup table.
 *
 * Run by `composer generate` after `buf generate`. CI regenerates and diffs.
 */

const FIELD_BEHAVIOR_EXTENSION = 1052; // google.api.field_behavior
const FIELD_BEHAVIOR_REQUIRED = 2;

$root = dirname(__DIR__);
$metadataFile = $root . '/generated/A2A/Types/GPBMetadata/A2A.php';
$outputFile = $root . '/generated/A2A/Types/Meta/RequiredFields.php';

$descriptorBytes = extractDescriptorBytes((string) file_get_contents($metadataFile));
// The literal is a FileDescriptorSet; field 1 holds our single FileDescriptorProto.
$set = decodeMessage($descriptorBytes);
$file = decodeMessage((string) $set[1][0]);

$package = isset($file[2][0]) ? $file[2][0] : '';
$required = [];
foreach ($file[4] ?? [] as $messageBytes) {
    collectRequired($messageBytes, $package, $required);
}
ksort($required);

$lines = [];
foreach ($required as $messageName => $fields) {
    $lines[] = sprintf("        '%s' => [%s],", $messageName, implode(', ', array_map(static fn (string $f): string => "'" . $f . "'", $fields)));
}

$php = <<<PHP
<?php
# Generated by scripts/generate-required-fields.php from a2a.proto. DO NOT EDIT.

declare(strict_types=1);

namespace A2A\Types\Meta;

/**
 * Fields marked `(google.api.field_behavior) = REQUIRED` in a2a.proto,
 * keyed by fully qualified message name, using proto (snake_case) field names.
 */
final class RequiredFields
{
    /** @var array<string, list<string>> */
    public const BY_MESSAGE = [
%s
    ];

    /**
     * @return list<string>
     */
    public static function forMessage(string \$fullName): array
    {
        return self::BY_MESSAGE[\$fullName] ?? [];
    }
}

PHP;

if (!is_dir(dirname($outputFile))) {
    mkdir(dirname($outputFile), 0777, true);
}
file_put_contents($outputFile, sprintf($php, implode("\n", $lines)));
echo 'Wrote ' . substr($outputFile, strlen($root) + 1) . ' (' . count($required) . " messages)\n";

/**
 * @param array<string, list<string>> $required
 */
function collectRequired(string $messageBytes, string $scope, array &$required): void
{
    $message = decodeMessage($messageBytes);
    $name = $scope . '.' . ($message[1][0] ?? '');

    $fields = [];
    foreach ($message[2] ?? [] as $fieldBytes) {
        $field = decodeMessage($fieldBytes);
        $options = isset($field[8][0]) ? decodeMessage($field[8][0]) : [];
        foreach ($options[FIELD_BEHAVIOR_EXTENSION] ?? [] as $behavior) {
            // Unpacked values arrive as ints, packed ones as a length-delimited blob.
            $values = is_int($behavior) ? [$behavior] : decodePackedVarints($behavior);
            if (in_array(FIELD_BEHAVIOR_REQUIRED, $values, true)) {
                $fields[] = (string) $field[1][0];
                break;
            }
        }
    }
    if ($fields !== []) {
        $required[$name] = $fields;
    }

    foreach ($message[3] ?? [] as $nestedBytes) {
        collectRequired($nestedBytes, $name, $required);
    }
}

/**
 * Minimal protobuf wire-format reader: field number => list of raw values
 * (int for varints, string for length-delimited). Enough for descriptors.
 *
 * @return array<int, list<int|string>>
 */
function decodeMessage(string $bytes): array
{
    $out = [];
    $offset = 0;
    $length = strlen($bytes);
    while ($offset < $length) {
        $key = readVarint($bytes, $offset);
        $fieldNumber = $key >> 3;
        switch ($key & 7) {
            case 0:
                $out[$fieldNumber][] = readVarint($bytes, $offset);
                break;
            case 1:
                $out[$fieldNumber][] = substr($bytes, $offset, 8);
                $offset += 8;
                break;
            case 2:
                $size = readVarint($bytes, $offset);
                $out[$fieldNumber][] = substr($bytes, $offset, $size);
                $offset += $size;
                break;
            case 5:
                $out[$fieldNumber][] = substr($bytes, $offset, 4);
                $offset += 4;
                break;
            default:
                throw new RuntimeException('Unsupported wire type in descriptor');
        }
    }

    return $out;
}

/**
 * @return list<int>
 */
function decodePackedVarints(string $bytes): array
{
    $values = [];
    $offset = 0;
    while ($offset < strlen($bytes)) {
        $values[] = readVarint($bytes, $offset);
    }

    return $values;
}

function readVarint(string $bytes, int &$offset): int
{
    $result = 0;
    $shift = 0;
    do {
        $byte = ord($bytes[$offset++]);
        $result |= ($byte & 0x7F) << $shift;
        $shift += 7;
    } while ($byte & 0x80);

    return $result;
}

function extractDescriptorBytes(string $source): string
{
    // The descriptor is the only double-quoted string literal passed to
    // internalAddGeneratedFile(); decode its escapes without eval().
    $tokens = token_get_all($source);
    $seenCall = false;
    foreach ($tokens as $token) {
        if (is_array($token) && $token[0] === T_STRING && $token[1] === 'internalAddGeneratedFile') {
            $seenCall = true;
        }
        if ($seenCall && is_array($token) && $token[0] === T_CONSTANT_ENCAPSED_STRING) {
            return stripcslashes(substr($token[1], 1, -1));
        }
    }

    throw new RuntimeException('Descriptor literal not found in GPBMetadata/A2A.php');
}
